amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.5
    default_nav_through_poses_bt_xml: "/home/jw/robot/ros_ws/src/ExaRobot_ROS2/exa_robot/config/navigate_through_poses_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/home/jw/robot/ros_ws/src/ExaRobot_ROS2/exa_robot/config/navigate_to_pose_w_replanning_and_recovery.xml"
    #default_nav_to_pose_bt_xml: "/home/nvidia/robot/exa/ros_ws/src/ExaRobot_ROS2/exa_robot/config/navigate_follow_point.xml"

    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    plugin_lib_names:
    #action
    - nav2_back_up_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_controller_selector_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_wait_action_bt_node
    #condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_transform_available_condition_bt_node
    #control
    - nav2_pipeline_sequence_bt_node
    - nav2_recovery_node_bt_node
    - nav2_round_robin_node_bt_node
    #decorator
    - nav2_distance_controller_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_rate_controller_bt_node
    - nav2_single_trigger_bt_node
    - nav2_speed_controller_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

# controller_server:
#   ros__parameters:
#     use_sim_time: True
#     controller_frequency: 10.0
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.5
#     min_theta_velocity_threshold: 0.001
#     progress_checker_plugin: "progress_checker"
#     goal_checker_plugins: ["goal_checker"]
#     controller_plugins: ["FollowPath"]

#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
#       movement_time_allowance: 10.0
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25
#       stateful: True
#     FollowPath:
#       plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
#       desired_linear_vel: 0.5
#       lookahead_dist: 0.6
#       min_lookahead_dist: 0.2
#       max_lookahead_dist: 0.9
#       lookahead_time: 3.5
#       rotate_to_heading_angular_vel: 1.8
#       transform_tolerance: 0.1
#       use_velocity_scaled_lookahead_dist: false
#       min_approach_linear_velocity: 0.05
#       approach_velocity_scaling_dist: 0.6
#       use_collision_detection: true
#       max_allowed_time_to_collision_up_to_carrot: 2.0
#       use_regulated_linear_velocity_scaling: true
#       use_cost_regulated_linear_velocity_scaling: false
#       regulated_linear_scaling_min_radius: 0.9
#       regulated_linear_scaling_min_speed: 0.25
#       use_rotate_to_heading: true
#       allow_reversing: false
#       rotate_to_heading_min_angle: 0.785
#       max_angular_accel: 3.2
#       max_robot_pose_search_dist: 10.0
#       use_interpolation: false



controller_server:
  ros__parameters:
    odom_topic: /odom
    use_sim_time: True
    controller_frequency: 10.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"

      teb_autosize: 1.0
      dt_ref: 0.3
      dt_hysteresis: 0.03 #0.1
      max_samples: 50 #500
      global_plan_overwrite_orientation: True #False
      allow_init_with_backwards_motion: False
      max_global_plan_lookahead_dist: 5.0 #3.0
      global_plan_viapoint_sep: 1.0 #0.3
      global_plan_prune_distance: 1.0
      exact_arc_length: False
      feasibility_check_no_poses: 3 #2
      publish_feedback: False
          
      # Robot
      max_vel_x: 0.5
      max_vel_x_backwards: 0.0
      max_vel_theta: 0.4
      acc_lim_x: 2.0
      acc_lim_theta: 2.0

      footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "circular"
        # types: "polygon"
        radius: 0.32 # for type "circular"
        # vertices: [[0.202,0.245], [-0.439,0.245], [-0.439,-0.245], [0.202,-0.245]]
 
      # GoalTolerance
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25  
      free_goal_vel: False
          
      # Obstacles
          
      min_obstacle_dist: 0.32 #0.44 #0.27
      inflation_dist: 0.30 #0.5 #0.6
      include_costmap_obstacles: True
      costmap_obstacles_behind_robot_dist: 1.5 #1.0
      obstacle_poses_affected: 30 #15

      dynamic_obstacle_inflation_dist: 0.2 #0.4 #0.6
      include_dynamic_obstacles: False #True 

      costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
      costmap_converter_spin_thread: True
      costmap_converter_rate: 5

      # Optimization
          
      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: True
      optimization_verbose: False
      penalty_epsilon: 0.04 #0.1
      obstacle_cost_exponent: 4.0
      weight_max_vel_x: 1.0 #0.5
      weight_max_vel_theta: 1.0 #0.5
      weight_acc_lim_x:  0.0 #0.5
      weight_acc_lim_theta: 0.0 #10.5
      weight_kinematics_nh: 1000.0
      weight_kinematics_forward_drive: 1000.0 #3.0
      weight_kinematics_turning_radius: 1.0
      weight_optimaltime: 1.0 # must be > 0
      weight_shortest_path: 0.0
      weight_obstacle: 10.0 #100.0
      weight_inflation: 0.2
      weight_dynamic_obstacle: 10.0 # not in use yet
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 1.0 #50.0
      weight_adapt_factor: 2.0

      # Homotopy Class Planner

      enable_homotopy_class_planning: false #True
      enable_multithreading: True
      max_number_classes: 4
      selection_cost_hysteresis: 1.0 #5.0
      selection_prefer_initial_plan: 1.0
      selection_obst_cost_scale: 1.0
      selection_alternative_time_cost: False #True

      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_heading_threshold: 0.45
      switching_blocking_period: 0.0
      viapoints_all_candidates: True
      delete_detours_backwards: True
      max_ratio_detours_duration_best_duration: 3.0
      visualize_hc_graph: False
      visualize_with_time_as_z_axis_scale: 0.0

      # Recovery
      
      shrink_horizon_backup: True
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: True
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0
     
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True



local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: True
      rolling_window: true
      width: 15
      height: 15
      resolution: 0.03
      robot_radius: 0.22
      unknown_cost_value : 200
      plugins: [
                "obstacle_layer",
                "stvl_layer",
                "inflation_layer"
                ]
      # plugins: ["voxel_layer","stvl_layer","inflation_layer"]
      # plugins: ["voxel_layer", "inflation_layer"]



      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.5
          raytrace_min_range: 0.0
          obstacle_max_range: 15.0
          obstacle_min_range: 0.0
     
        
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 1.
        decay_model: 0
        voxel_size: 0.01
        track_unknown_space: true
        unknown_threshold: 15
        mark_threshold: 0
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        map_save_duration: 60.0
        observation_sources: pointcloud clip
        pointcloud:
          data_type: PointCloud2
          topic: /camera_front_down/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 3.0
          min_obstacle_height: 0.05
          max_obstacle_height: 0.8
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: true
          voxel_min_points: 3 
          clear_after_reading: true
          # max_z: 2.0
          # min_z: 0.08
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 30.0
          model_type: 0
      clip: 
          data_type: PointCloud2
          topic: /camera_front_down/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.0
          min_obstacle_height: -0.3
          max_obstacle_height: -0.2
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: true
          clear_after_reading: true
          # max_z: 2.0
          min_z: -0.5
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 1.0
          model_type: 0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # cost_scaling_factor: 3.0
        # inflation_radius: 0.30
        cost_scaling_factor: 3.58 #2.58
        inflation_radius: 1.75 #1.75

      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      width: 10
      height: 10
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: true
      unknown_cost_value : 200
      plugins: ["static_layer",
                "obstacle_layer",
                "stvl_layer", 
                "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.5
          raytrace_min_range: 0.0
          obstacle_max_range: 15.0
          obstacle_min_range: 0.0

      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 1.
        decay_model: 0
        voxel_size: 0.01
        track_unknown_space: true
        unknown_threshold: 15
        mark_threshold: 0
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0  
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        map_save_duration: 60.0
        observation_sources: pointcloud clip
        pointcloud:
          data_type: PointCloud2
          topic: /camera_front_down/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 3.0
          min_obstacle_height: 0.05
          max_obstacle_height: 0.8
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: true
          voxel_min_points: 3  
          clear_after_reading: true
          # max_z: 2.0
          # min_z: 0.05
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 30.0
          model_type: 0
      clip: 
          data_type: PointCloud2
          topic: /camera_front_down/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.0
          min_obstacle_height: -0.3
          max_obstacle_height: -0.2
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: true
          clear_after_reading: true
          # max_z: 2.0
          min_z: -0.5
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 10.0
          model_type: 0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
       

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # cost_scaling_factor: 3.0
        # inflation_radius: 0.30
        cost_scaling_factor: 3.58 #2.58
        inflation_radius: 1.75 #1.75
        inflate_unknown : True

      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True


planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: false
# planner_server:
#   ros__parameters:
#     planner_plugins: ["GridBased"]
#     use_sim_time: True

#     GridBased:
#       plugin: "nav2_smac_planner/SmacPlannerHybrid"
#       downsample_costmap: false           # whether or not to downsample the map
#       downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
#       allow_unknown: true                 # allow traveling in unknown space
#       max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
#       max_planning_time: 5.0              # max time in s for planner to plan, smooth
#       motion_model_for_search: "DUBIN"    # Hybrid-A* Dubin, Redds-Shepp
#       angle_quantization_bins: 72         # Number of angle bins for search
#       analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
#       analytic_expansion_max_length: 3.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
#       minimum_turning_radius: 0.40        # minimum turning radius in m of path / vehicle
#       reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
#       change_penalty: 0.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
#       non_straight_penalty: 1.2           # Penalty to apply if motion is non-straight, must be => 1
#       cost_penalty: 2.0                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
#       retrospective_penalty: 0.015
#       lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
#       cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
#       smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path

#       smoother:
#         max_iterations: 1000
#         w_smooth: 0.3
#         w_data: 0.2
#         tolerance: 1.0e-10
#         do_refinement: true


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
