# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking
velocity_smoother:
  ros__parameters:
    # limits
    speed_lim_v: 0.4
    speed_lim_w: 1.0

    accel_lim_v: 0.2
    accel_lim_w: 0.9
    
    # multiply the acceleration limit by this to permit faster decellerations
    decel_factor: 5.0

    # recompute smoothed velocities at this rate
    frequency: 10.0

    # feedback type:
    #  0 - none
    #  1 - odometry
    #  2 - actual commanded velocity (e.g. after it's been piped through a mux)
    feedback: 2
